--Tabla customers 
--CREATE

CREATE OR REPLACE PROCEDURE AddCustomer (
    p_CUSTOMER_ID IN NUMBER,
    p_CUST_FIRST_NAME IN VARCHAR2,
    p_CUST_LAST_NAME IN VARCHAR2,
    p_CREDIT_LIMIT IN NUMBER,
    p_CUST_EMAIL IN VARCHAR2,
    p_INCOME_LEVEL IN VARCHAR2,
    p_REGION IN VARCHAR2
) AS
BEGIN
    INSERT INTO CUSTOMERS (CUSTOMER_ID, CUST_FIRST_NAME, CUST_LAST_NAME, CREDIT_LIMIT, CUST_EMAIL, INCOME_LEVEL, REGION)
    VALUES (p_CUSTOMER_ID, p_CUST_FIRST_NAME, p_CUST_LAST_NAME, p_CREDIT_LIMIT, p_CUST_EMAIL, p_INCOME_LEVEL, p_REGION);
END;

--UPDATE 

CREATE OR REPLACE PROCEDURE UpdateCustomer (
    p_CUSTOMER_ID IN NUMBER,
    p_CUST_FIRST_NAME IN VARCHAR2,
    p_CUST_LAST_NAME IN VARCHAR2,
    p_CREDIT_LIMIT IN NUMBER,
    p_CUST_EMAIL IN VARCHAR2,
    p_INCOME_LEVEL IN VARCHAR2,
    p_REGION IN VARCHAR2
) AS
BEGIN
    UPDATE CUSTOMERS
    SET CUST_FIRST_NAME = p_CUST_FIRST_NAME,
        CUST_LAST_NAME = p_CUST_LAST_NAME,
        CREDIT_LIMIT = p_CREDIT_LIMIT,
        CUST_EMAIL = p_CUST_EMAIL,
        INCOME_LEVEL = p_INCOME_LEVEL,
        REGION = p_REGION
    WHERE CUSTOMER_ID = p_CUSTOMER_ID;
END;

--DELETE

CREATE OR REPLACE PROCEDURE DeleteCustomer (
    p_CUSTOMER_ID IN NUMBER
) AS
BEGIN
    DELETE FROM CUSTOMERS WHERE CUSTOMER_ID = p_CUSTOMER_ID;
END;

--TABLA ORDER_ITEMS

--CREATE

CREATE OR REPLACE PROCEDURE AddOrderItem (
    p_ORDER_ID IN NUMBER,
    p_LINE_ITEM_ID IN NUMBER,
    p_PRODUCT_ID IN NUMBER,
    p_UNIT_PRICE IN NUMBER,
    p_QUANTITY IN NUMBER
) AS
BEGIN
    INSERT INTO ORDER_ITEMS (ORDER_ID, LINE_ITEM_ID, PRODUCT_ID, UNIT_PRICE, QUANTITY)
    VALUES (p_ORDER_ID, p_LINE_ITEM_ID, p_PRODUCT_ID, p_UNIT_PRICE, p_QUANTITY);
END;

--UPDATE

CREATE OR REPLACE PROCEDURE UpdateOrderItem (
    p_ORDER_ID IN NUMBER,
    p_LINE_ITEM_ID IN NUMBER,
    p_PRODUCT_ID IN NUMBER,
    p_UNIT_PRICE IN NUMBER,
    p_QUANTITY IN NUMBER
) AS
BEGIN
    UPDATE ORDER_ITEMS
    SET PRODUCT_ID = p_PRODUCT_ID,
        UNIT_PRICE = p_UNIT_PRICE,
        QUANTITY = p_QUANTITY
    WHERE ORDER_ID = p_ORDER_ID AND LINE_ITEM_ID = p_LINE_ITEM_ID;
END;

--DELETE

CREATE OR REPLACE PROCEDURE DeleteOrderItem (
    p_ORDER_ID IN NUMBER,
    p_LINE_ITEM_ID IN NUMBER
) AS
BEGIN
    DELETE FROM ORDER_ITEMS
    WHERE ORDER_ID = p_ORDER_ID AND LINE_ITEM_ID = p_LINE_ITEM_ID;
END;

--TABLA ORDERS

CREATE OR REPLACE PROCEDURE AddOrder (
    p_ORDER_ID IN NUMBER,
    p_ORDER_DATE IN VARCHAR2,
    p_ORDER_MODE IN VARCHAR2,
    p_CUSTOMER_ID IN NUMBER,
    p_ORDER_STATUS IN NUMBER,
    p_ORDER_TOTAL IN NUMBER,
    p_SALES_REP_ID IN NUMBER,
    p_PROMOTION_ID IN NUMBER
) AS
BEGIN
    INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL, SALES_REP_ID, PROMOTION_ID)
    VALUES (p_ORDER_ID, TO_TIMESTAMP(p_ORDER_DATE,'DD-MON-RR HH.MI.SS.FF AM','NLS_DATE_LANGUAGE=American'), p_ORDER_MODE, p_CUSTOMER_ID, p_ORDER_STATUS, p_ORDER_TOTAL, p_SALES_REP_ID, p_PROMOTION_ID);
END;

--UPDATE

CREATE OR REPLACE PROCEDURE UpdateOrder (
    p_ORDER_ID IN NUMBER,
    p_ORDER_DATE IN VARCHAR2,
    p_ORDER_MODE IN VARCHAR2,
    p_CUSTOMER_ID IN NUMBER,
    p_ORDER_STATUS IN NUMBER,
    p_ORDER_TOTAL IN NUMBER,
    p_SALES_REP_ID IN NUMBER,
    p_PROMOTION_ID IN NUMBER
) AS
BEGIN
    UPDATE ORDERS
    SET ORDER_DATE = p_ORDER_DATE,
        ORDER_MODE = TO_TIMESTAMP(p_ORDER_DATE,'DD-MON-RR HH.MI.SS.FF AM','NLS_DATE_LANGUAGE=American'),
        CUSTOMER_ID = p_CUSTOMER_ID,
        ORDER_STATUS = p_ORDER_STATUS,
        ORDER_TOTAL = p_ORDER_TOTAL,
        SALES_REP_ID = p_SALES_REP_ID,
        PROMOTION_ID = p_PROMOTION_ID
    WHERE ORDER_ID = p_ORDER_ID;
END;

--DELETE

CREATE OR REPLACE PROCEDURE DeleteOrder (
    p_ORDER_ID IN NUMBER
) AS
BEGIN
    DELETE FROM ORDERS WHERE ORDER_ID = p_ORDER_ID;
END;

--TABLA PRODUCT_INFORMATION

CREATE OR REPLACE PROCEDURE AddProduct (
    p_PRODUCT_ID IN NUMBER,
    p_PRODUCT_NAME IN VARCHAR2,
    p_PRODUCT_DESCRIPTION IN VARCHAR2,
    p_CATEGORY_ID IN NUMBER,
    p_WEIGHT_CLASS IN NUMBER,
    p_WARRANTY_PERIOD IN INTERVAL YEAR TO MONTH,
    p_SUPPLIER_ID IN NUMBER,
    p_PRODUCT_STATUS IN VARCHAR2,
    p_LIST_PRICE IN NUMBER,
    p_MIN_PRICE IN NUMBER,
    p_CATALOG_URL IN VARCHAR2
) AS
BEGIN
    INSERT INTO PRODUCT_INFORMATION (PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, WEIGHT_CLASS, WARRANTY_PERIOD, SUPPLIER_ID, PRODUCT_STATUS, LIST_PRICE, MIN_PRICE, CATALOG_URL)
    VALUES (p_PRODUCT_ID, p_PRODUCT_NAME, p_PRODUCT_DESCRIPTION, p_CATEGORY_ID, p_WEIGHT_CLASS, p_WARRANTY_PERIOD, p_SUPPLIER_ID, p_PRODUCT_STATUS, p_LIST_PRICE, p_MIN_PRICE, p_CATALOG_URL);
END;

--UPDATE

CREATE OR REPLACE PROCEDURE UpdateProduct (
    p_PRODUCT_ID IN NUMBER,
    p_PRODUCT_NAME IN VARCHAR2,
    p_PRODUCT_DESCRIPTION IN VARCHAR2,
    p_CATEGORY_ID IN NUMBER,
    p_WEIGHT_CLASS IN NUMBER,
    p_WARRANTY_PERIOD IN INTERVAL YEAR TO MONTH,
    p_SUPPLIER_ID IN NUMBER,
    p_PRODUCT_STATUS IN VARCHAR2,
    p_LIST_PRICE IN NUMBER,
    p_MIN_PRICE IN NUMBER,
    p_CATALOG_URL IN VARCHAR2
) AS
BEGIN
    UPDATE PRODUCT_INFORMATION
    SET PRODUCT_NAME = p_PRODUCT_NAME,
        PRODUCT_DESCRIPTION = p_PRODUCT_DESCRIPTION,
        CATEGORY_ID = p_CATEGORY_ID,
        WEIGHT_CLASS = p_WEIGHT_CLASS,
        WARRANTY_PERIOD = p_WARRANTY_PERIOD,
        SUPPLIER_ID = p_SUPPLIER_ID,
        PRODUCT_STATUS = p_PRODUCT_STATUS,
        LIST_PRICE = p_LIST_PRICE,
        MIN_PRICE = p_MIN_PRICE,
        CATALOG_URL = p_CATALOG_URL
    WHERE PRODUCT_ID = p_PRODUCT_ID;
END;

--DELETE

CREATE OR REPLACE PROCEDURE DeleteProduct (
    p_PRODUCT_ID IN NUMBER
) AS
BEGIN
    DELETE FROM PRODUCT_INFORMATION WHERE PRODUCT_ID = p_PRODUCT_ID;
END;